version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: webshop-laravel-php
    volumes:
      - .:/app:delegated
      - vendor-files:/app/vendor
      - node-modules:/app/node_modules
    depends_on:
      - db
      - redis
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: laravel

      REDIS_HOST: redis

      SESSION_DRIVER: redis
      CACHE_DRIVER: redis

      APP_ENV: local
      APP_URL: http://localhost
      APP_DEBUG: 1
      TIMEZONE: Europe/Amsterdam

      DEBUGBAR_ENABLED: 1
      DEBUGBAR_THEME: dark
  node:
    image: node:16-alpine
    container_name: webshop-laravel-node
    command: tail -F /dev/null
    working_dir: /app
    volumes:
      - .:/app:delegated
      - node-modules:/app/node_modules
      - /app/app
      - /app/bootstrap
      - /app/config
      - /app/database
      - /app/routes
      - /app/tests
      - /app/vendor
  nginx:
    image: nginx:1.19-alpine
    container_name: webshop-laravel-nginx
    volumes:
      - .:/app:delegated
      - vendor-files:/app/vendor
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
  db:
    image: postgres:13.2
    container_name: webshop-laravel-db
    volumes:
      - pgsql-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: laravel
      POSTGRES_USER: laravel
      POSTGRES_DB: laravel
  redis:
    image: redis:6.2.2-alpine
    container_name: webshop-laravel-redis

volumes:
  pgsql-data:
  vendor-files:
  node-modules:
