version: '3.9'

services:
  php:
    build:
      context: .
      dockerfile: ./.docker/php/Dockerfile
    container_name: webshop-laravel-php
    volumes:
      - .:/app:delegated
    depends_on:
      - db
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USER: laravel
      DB_PASSWORD: laravel

      APP_ENV: local
      APP_URL: http://localhost
      APP_DEBUG: 1
      TIMEZONE: Europe/Amsterdam
      MAIL_DRIVER: log
  nginx:
    image: nginx:1.19-alpine
    container_name: webshop-laravel-nginx
    volumes:
      - .:/app:delegated
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
  db:
    image: postgres:13.2
    container_name: webshop-laravel-db
    volumes:
      - webshop-laravel-db-data:/var/lib/postgresql/data:cached
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: laravel
      POSTGRES_USER: laravel
      POSTGRES_DB: laravel

volumes:
  webshop-laravel-db-data:
