name: CI
on: push
jobs:
  Test:
    runs-on: ubuntu-20.04
    container:
      image: php:8.0-alpine
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy .env
        run: '[ ! -e ".env" ] && cp .env.example .env'
      - name: Install Composer Dependencies
        run: composer install -q --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Install NPM Dependencies
        run: npm install --silent
      - name: Build FE
        run: npm run production
      - name: Generate key
        run: php artisan key:generate
      - name: Execute unit tests
        run: php artisan test
