name: CI
on: push
jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup php 8.0
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.0'
      - name: Check php version
        run: php --version
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Copy .env
        run: '[ ! -e ".env" ] && cp .env.example .env'
      - name: Install Composer Dependencies
        run: composer install -q --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Install NPM Dependencies
        run: npm install --silent
      - name: Build FE
        run: npm run production
      - name: Generate key
        run: php artisan key:generate
      - name: Execute unit tests
        run: php artisan test
